:categories:
  - Safe
  - Original Characters
  - Canon Characters
  - Shipping
  - Pony
  - Anthro
  - Human and EqG
  - Original Species
  - Comics
  - NSFW
  - Fetish Art
  - Violence and Gore
  - Requests

:item_types:
  - Sketch
  - Colored Sketch
  - Inked
  - Flat Color
  - Vector
  - Cel Shaded
  - Fully Shaded
  - Traditional
  - Pixel Art
  - Animation
  - Crafted Item
  - Sculpture
  - Plushie
  - Other
